export const GET_REQUEST_NEWS = "GET_REQUEST_NEWS"
export const GET_SUCCESS_NEWS = "GET_SUCCESS_NEWS"
export const GET_FAIL_NEWS = "GET_FAIL_NEWS"

export const GET_REQUEST_FAV = "GET_REQUEST_FAV"
export const GET_SUCCESS_FAV = "GET_SUCCESS_FAV"
export const GET_FAIL_FAV = "GET_FAIL_FAV"

export const GET_SUCCESS_TOGGLE = "GET_SUCCESS_TOGGLE"

